[package]
name = "rusty_manager_bot"
version = "0.3.0"
authors = ["Ilya Venner <ilyavenner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
carapax = "0.8.0"
log = "0.4.11"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4.19"
tokio = { version = "0.2.4", features = ["full"] }
async-trait = "0.1.40"
snafu = "0.6.9"
clap = "2.33.3"

[[bin]]
name = "rusty-manager-bot"
path = "src/main.rs"
